<?xml version="1.0" encoding="utf-8"?><Database Name="MasterBox" Class="AuthDBControlDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=mbox-mssql.c2apojdl5mfi.ap-southeast-1.rds.amazonaws.com;Initial Catalog=MasterBox;Persist Security Info=True;User ID=masterboxadmin" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="MasterBoxConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.mb_users" Member="mb_users">
    <Type Name="mb_user">
      <Column Name="userid" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="userImage" Type="System.Data.Linq.Binary" DbType="VarBinary(255)" CanBeNull="true" />
      <Column Name="fName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="lName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="birthDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="verified" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="timeZone" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="mbrType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="regTimestamp" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Column Name="mbrStartDate" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="mbrExpireDate" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Association Name="mb_user_mb_auth" Member="mb_auths" ThisKey="userid" OtherKey="userid" Type="mb_auth" />
    </Type>
  </Table>
  <Table Name="dbo.mb_auth" Member="mb_auths">
    <Type Name="mb_auth">
      <Column Name="username" Type="System.String" DbType="VarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="userid" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="pwd_salt" Type="System.String" DbType="VarChar(70) NOT NULL" CanBeNull="false" />
      <Column Name="login_seed" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="lastlogin" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="totpsecret" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Association Name="mb_user_mb_auth" Member="mb_user" ThisKey="userid" OtherKey="userid" Type="mb_user" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
</Database>